<?php
/**
 * ============================================================================
 * SYSTEM TEST REPORT: Full API Pipeline
 * ============================================================================
 * Description:
 * This System test covers the full stack data flow, from initial configuration
 * (creating custom categories), to batch processing transactions linearly,
 * logging multi-level inflows and outflows, and finally asserting that the 
 * JSON response generated by the `/api/data.php` endpoint calculates an identical 
 * total dashboard balance to the actual transactional math.
 * 
 * How to Run:
 * 1. Ensure you are in the project root directory (`track_it`).
 * 2. Ensure MySQL is running on `localhost` with the `trackit_db` database active.
 * 3. Execute: `vendor/bin/phpunit tests/system/FullSystemTest.php`
 * ============================================================================
 */

use PHPUnit\Framework\TestCase;

class FullSystemTest extends TestCase
{
    private $pdo;

    protected function setUp(): void
    {
        $host = 'localhost';
        $db   = 'trackit_db';
        $user = 'root';
        $pass = '';
        $this->pdo = new PDO("mysql:host=$host;dbname=$db;charset=utf8mb4", $user, $pass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
        ]);
        $GLOBALS['pdo'] = $this->pdo;
        $GLOBALS['pdo_mock'] = $this->pdo; 

        // Flush for system test user ID 100
        $this->pdo->exec("DELETE FROM transactions WHERE user_id = 100");
        $this->pdo->exec("DELETE FROM wishes WHERE user_id = 100");
        $this->pdo->exec("DELETE FROM categories WHERE user_id = 100");
        $this->pdo->exec("DELETE FROM users WHERE id = 100");
        $this->pdo->exec("INSERT INTO users (id, username, password, email, balance) VALUES (100, 'system_user', 'hash', 'sys@trackit.com', 0)");
        
        $_SESSION['user_id'] = 100;
        if (!defined('TEST_MODE')) define('TEST_MODE', true);
    }

    /**
     * System Testing: Verify the end-to-end data fidelity across all interconnected APIs.
     * Scenario: Month of operations including custom categories, incomes, expenses, wishes.
     */
    public function testSystemDataIntegrity()
    {
        // 1. Add Custom Categories (System boundary limit check)
        $_SERVER['REQUEST_METHOD'] = 'POST';
        $GLOBALS['INPUT_DATA'] = json_encode(['name' => 'Salary', 'type' => 'inflow']);
        ob_start();
        require __DIR__ . '/../../api/categories.php';
        ob_end_clean();
        
        $GLOBALS['INPUT_DATA'] = json_encode(['name' => 'Rent', 'type' => 'outflow']);
        ob_start();
        require __DIR__ . '/../../api/categories.php';
        ob_end_clean();
        
        $stmt = $this->pdo->prepare("SELECT id FROM categories WHERE user_id = 100 AND name = 'Salary'");
        $stmt->execute();
        $salaryCat = $stmt->fetchColumn() ?: 1;

        $stmt = $this->pdo->prepare("SELECT id FROM categories WHERE user_id = 100 AND name = 'Rent'");
        $stmt->execute();
        $rentCat = $stmt->fetchColumn() ?: 2;

        // 2. Perform Transactions
        $this->makeTransaction('inflow', $salaryCat, 5000, 'Monthly Pay');
        $this->makeTransaction('outflow', $rentCat, 1500, 'Apartment');
        $this->makeTransaction('outflow', null, 250, 'Groceries');

        // 3. Setup Wish & Fund it
        $_SERVER['REQUEST_METHOD'] = 'POST';
        $GLOBALS['mock_input'] = ['title' => 'Vacation', 'target_amount' => 1000];
        $GLOBALS['mock_method'] = 'POST';
        ob_start();
        eval('?>' . file_get_contents(__DIR__ . '/../../api/wishes.php'));
        ob_end_clean();

        $wishId = $this->pdo->lastInsertId();

        $_SERVER['REQUEST_METHOD'] = 'PUT';
        $GLOBALS['mock_input'] = ['id' => $wishId, 'amount' => 200];
        $GLOBALS['mock_method'] = 'PUT';
        ob_start();
        eval('?>' . file_get_contents(__DIR__ . '/../../api/wishes.php'));
        ob_end_clean();

        // 4. Verification points (System Aggregation)
        // Checking data.php (Summary Dashboard API)
        ob_start();
        $summary = require __DIR__ . '/../../api/data.php';
        ob_end_clean();
        
        // System math:
        // Inflow: 5000
        // Outflow: 1500 (Rent) + 250 (Groceries) + 200 (Funded Wish) = 1950
        // Balance: 3050

        $this->assertEquals("5,000.00", $summary['inflow'], "System computed inflow incorrectly.");
        $this->assertEquals("1,950.00", $summary['outflow'], "System computed outflow incorrectly.");
        $this->assertEquals("3,050.00", $summary['balance'], "System computed balance incorrectly.");
    }

    private function makeTransaction($type, $cat_id, $amount, $desc) {
        $_SERVER['REQUEST_METHOD'] = 'POST';
        $GLOBALS['INPUT_DATA'] = json_encode([
            'type' => $type,
            'category_id' => $cat_id,
            'amount' => $amount,
            'description' => $desc
        ]);
        ob_start();
        require __DIR__ . '/../../api/transaction.php';
        ob_end_clean();
    }
}
